sudo: required
branches:
  only:
    - master

language: node_js

node_js:
  - node
script:
  - npm run test-ci
  - npm run build-ci
before_deploy:
  - cd dist/ngx-dom-navigator

deploy:
  provider: npm
  email: serhatkaya.abarth@gmail.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
